Kotlinify codebase
android/nowinandroid pull request #1039
Opened 2023-11-16 22:46 UTC by SimonMarquis

- Remove unnecessary nullable types
- Replace no-op  method bodies with Unit
- Convert to expression body
- Replace if with when
- Remove braces from 'when' entries
- Remove braces from if statement
- Convert to single line lambda
- oneline if/returns
- Replace 'contains' call with 'in' operator

Following this refactor, it could be great to envision a more "strict" code formatter like ktlint 1.0 (we are currently stuck at 0.48.1)

2023-12-21 17:03 UTC, dturner commented on core/designsystem/src/main/kotlin/com/google/samples/apps/nowinandroid/core/designsystem/component/scrollbar/ScrollbarExt.kt
> +    fold(0f) { acc, it -> acc + selector(it) }
Just trying to make this clearer for a first time reader
```suggestion
    fold(initial = 0f) { accumulator, listItem -> accumulator + selector(listItem) }
```

2023-12-21 17:10 UTC, dturner commented on feature/bookmarks/src/main/kotlin/com/google/samples/apps/nowinandroid/feature/bookmarks/navigation/BookmarksNavigation.kt
>      this.navigate(BOOKMARKS_ROUTE, navOptions)
brackets could also be removed so becomes

```
fun NavController.navigateToBookmarks(navOptions: NavOptions) =
    this.navigate(BOOKMARKS_ROUTE, navOptions)
```

2023-12-21 17:10 UTC, dturner commented on feature/foryou/src/main/kotlin/com/google/samples/apps/nowinandroid/feature/foryou/navigation/ForYouNavigation.kt
> +fun NavController.navigateToForYou(navOptions: NavOptions) {
Brackets can be removed

2023-12-21 17:11 UTC, dturner commented on feature/interests/src/main/kotlin/com/google/samples/apps/nowinandroid/feature/interests/navigation/InterestsNavigation.kt
> +fun NavController.navigateToInterestsGraph(navOptions: NavOptions) {
Brackets can be removed

2023-12-21 17:12 UTC, dturner commented on feature/bookmarks/src/main/kotlin/com/google/samples/apps/nowinandroid/feature/bookmarks/navigation/BookmarksNavigation.kt
>      this.navigate(BOOKMARKS_ROUTE, navOptions)
Also `this.` can be removed

2023-12-21 17:12 UTC, dturner commented on feature/foryou/src/main/kotlin/com/google/samples/apps/nowinandroid/feature/foryou/navigation/ForYouNavigation.kt
>      this.navigate(FOR_YOU_ROUTE, navOptions)
Also `this.` can be removed

2023-12-21 17:12 UTC, dturner commented on feature/interests/src/main/kotlin/com/google/samples/apps/nowinandroid/feature/interests/navigation/InterestsNavigation.kt
>      this.navigate(INTERESTS_GRAPH_ROUTE_PATTERN, navOptions)
Also `this.` can be removed

2023-12-21 17:13 UTC, dturner requested changes
Thanks very much for doing this. Idiomatic Kotlin is definitely nicer to read.

2023-12-21 17:15 UTC, dturner commented
> it could be great to envision a more "strict" code formatter like ktlint 1.0 (we are currently stuck at 0.48.1)

ktlint was merged in #1094

2023-12-21 17:53 UTC, SimonMarquis commented
@dturner PTAL, all your comments have been addressed 🤓

2023-12-22 13:17 UTC, dturner approved these changes

2023-12-22 13:21 UTC, dturner commented
@SimonMarquis I can't see any changes relating to the resolved changes - did you forget to push a commit?

2023-12-22 13:21 UTC, dturner requested changes
Waiting on suggested changes to be addressed

2023-12-22 13:50 UTC, SimonMarquis commented
@dturner these commits are:
- https://github.com/android/nowinandroid/pull/1039/commits/bdb10a687079ca0fd684fcbd31f729c84a9cfc51
- https://github.com/android/nowinandroid/pull/1039/commits/65f0d5b2d9cb1a743e91dbd7eb06423baf9c03a7
- https://github.com/android/nowinandroid/pull/1039/commits/6cd5958665f6c54aeb082a4acac28967b6dc946a
- https://github.com/android/nowinandroid/pull/1039/commits/b7a628ece5852dadbd4e2c69711ebbe24bcf45fc
- https://github.com/android/nowinandroid/pull/1039/commits/cd62fd5e01ddf8902dd5c86bd2f0a3b368f8e34f

2023-12-22 17:11 UTC, dturner commented
Oh apologies @SimonMarquis, for some reason I was reviewing outdated files which didn't have those commits.

2023-12-22 17:11 UTC, dturner approved these changes

2023-12-22 17:11 UTC, merged