Fixed grammar errors
android/nowinandroid pull request #200
Opened 2022-07-27 04:31 UTC by KaevonD

Fixed grammar errors in README.md

- allow immediate building and exploring of UI. -> exploring of the UI.
- implementation, and generally -> implementation and generally
- wiped after reach test. -> wiped after the reach test.
- manipulate the the state -> manipulate the state
- instead of checking that specific repository methods were called. -> instead of checking if
- for release builds that touched code -> that touch code

2022-07-29 11:01 UTC, dturner requested changes
Thanks for helping us to improve our docs. Added a couple of comments to address.

2022-08-01 16:41 UTC, calren commented
@KaevonD any chance you could address Don's comments so we can merge this? Thanks!

2022-08-02 01:35 UTC, KaevonD commented
Added your changes @dturner. Sorry for the wait @calren

2022-08-15 15:20 UTC, dturner approved these changes

2022-08-15 15:21 UTC, merged