Fixes #341 Defines enter & exit animations for OverlayLoadingWheel on…
android/nowinandroid pull request #358
Opened 2022-10-25 06:30 UTC by YuraLaguta

… ForYouScreen

Also added fadeOut because just animating it all the way up off the screen makes it ugly.

https://user-images.githubusercontent.com/1853043/197698785-76ff7eff-40ac-4b7a-9b2c-9b3a23f21d62.mov

2022-11-09 01:30 UTC, tunjid commented
Oh this is quite nice, lemme run it by the design team.

2022-11-09 13:43 UTC, tunjid approved these changes

2022-11-11 18:27 UTC, dturner commented
This is cool, thanks for submitting!

2022-11-12 05:31 UTC, tunjid commented
It seems the animations are causing the tests to have `StackOverflowException` when trying to assert that the progress bar is visible

2022-11-17 10:24 UTC, mmoczkowski requested changes
Thank you for your contribution Yuri! Could fix the spotless check please?

2022-11-21 13:33 UTC, mmoczkowski approved these changes
LGTM. Thank you for your contribution Yuri!

2022-11-21 13:35 UTC, mmoczkowski commented
> @mmoczkowski I've rebased on the main and pushed changes, back to square one with stack overflow during instrumentation test. Running tests locally on emulator on M1 works fine, application works fine. I'll have deeper look to find a root cause soon. Open for any suggestions

@YuraLaguta I restarted CI and all the tests passed 😄

2022-11-21 13:35 UTC, merged