added a string resources class UiText.kt in core:common this function…
android/nowinandroid pull request #501
Opened 2022-12-21 11:14 UTC by ALI-M0vS5a

… can be used in the entire project in order to have access to string resources also i have refactored the core:module by adding a manifest and the access to the core:common in core:common in the NewsResourceType.kt i have used the UiText.kt to change the description to stringResources

2022-12-21 17:50 UTC, dturner commented
Hey thanks for submitting this. It looks like a great solution.

2022-12-21 19:12 UTC, dturner commented
Please run `./gradlew --init-script gradle/init.gradle.kts spotlessApply` to fix the formatting issues.

2022-12-22 14:08 UTC, ALI-M0vS5a commented
hello.
should i remove the org.gradle.java.home=C\:\\Program Files\\Java\\jdk-11 from gradle.properties after running this 
./gradlew --init-script gradle/init.gradle.kts spotlessApply successfully?

2023-01-06 00:01 UTC, alexvanyo reviewed
I'm a bit confused by this PR, since it looks like `asString` and `unknownError` are both unused, and instances of `DynamicString` are never created.

Is the goal to have a more robust string mechanism for when we do need those methods?

2023-01-25 12:42 UTC, mmoczkowski requested changes
Remove the wrapper class and make description field a resource id instead of a string

2023-01-25 12:42 UTC, mmoczkowski commented on core/common/src/main/java/com/google/samples/apps/nowinandroid/core/uitext/UiText.kt
> +sealed class UiText {
This wrapper class is unnecessary noise and complexity imo

2023-01-25 12:42 UTC, mmoczkowski commented on core/model/src/main/java/com/google/samples/apps/nowinandroid/core/model/data/NewsResourceType.kt
> +    val description: UiText
I think it's more beneficial to simply store a resource id here

2023-03-30 09:34 UTC, mmoczkowski commented
Closing due to inactivity. If you still wish to submit this change, please create a new PR.

2023-03-30 09:34 UTC, closed without merging