Update Data Layer for search feature
android/nowinandroid pull request #659
Opened 2023-04-14 11:58 UTC by neelanshsahai

Change-Id: I0c5ec61fec4286c493b0a7472509eedf38fa9298

2023-04-14 12:35 UTC, hoc081098 commented on core/database/src/main/java/com/google/samples/apps/nowinandroid/core/database/dao/NewsResourceFtsDao.kt
> +    fun getCount(): Int
suspend function is better

2023-04-14 12:36 UTC, hoc081098 commented on core/data/src/main/java/com/google/samples/apps/nowinandroid/core/data/repository/RecentSearchRepository.kt
> +    fun getRecentSearchResults(searchQuery: String): List<NewsResource>
Should be suspend fun :))

2023-04-14 12:39 UTC, hoc081098 commented on core/database/src/main/java/com/google/samples/apps/nowinandroid/core/database/dao/TopicsFtsDao.kt
> +    fun getCount(): Int
As my above comment 😂😬

2023-04-14 12:43 UTC, hoc081098 commented on core/testing/build.gradle.kts
> +    implementation(project(mapOf("path" to ":core:database")))
```suggestion
    implementation(project(":core:database"))
```
And move it to below to make deps list sorted as the before

2023-04-14 12:49 UTC, hoc081098 commented on sync/work/src/main/java/com/google/samples/apps/nowinandroid/sync/workers/SyncWorker.kt
> +                .flatMapConcat { it.asFlow() }.toList()
getTopics() returns a infinity Flow.
So toList() will  not complete.

```suggestion
            topicRepository.getTopics()
                .first()
```

2023-04-14 12:49 UTC, hoc081098 commented on sync/work/src/main/java/com/google/samples/apps/nowinandroid/sync/workers/SyncWorker.kt
> +                .flatMapConcat { it.asFlow() }.toList()
getNewsResources() returns a infinity Flow.
So toList() will  not complete.


```suggestion
            newsRepository.getNewsResources()
                .first()
```

2023-04-17 02:52 UTC, thagikura commented on core/data/src/main/java/com/google/samples/apps/nowinandroid/core/data/repository/NewsRepository.kt
As in the design doc, I would create a dedicated repository for search that takes care of populating the fts tables and searching the fts tables.

2023-04-17 02:54 UTC, thagikura commented on core/data/src/main/java/com/google/samples/apps/nowinandroid/core/data/repository/RecentSearchRepository.kt
Recent searches will be implemented later, but probably can be in a follow up CL? Because there isn't a matching logic in the ViewModel nor the UI yet.

2023-04-17 02:54 UTC, thagikura commented on core/data/src/main/java/com/google/samples/apps/nowinandroid/core/data/repository/SearchContentsRepository.kt
I think populating Fts tables belong to this repository.

2023-04-17 02:55 UTC, thagikura commented on core/database/schemas/com.google.samples.apps.nowinandroid.core.database.NiaDatabase/12.json
You need to raise the version of the Database to avoid modifying the 12 version of the database schemea.

2023-04-17 03:04 UTC, thagikura requested changes
The CI is failing. 

Looks like styling issue is reported by spotless.

2023-04-17 03:06 UTC, thagikura commented on sync/work/src/main/java/com/google/samples/apps/nowinandroid/sync/workers/SyncWorker.kt
> +                .map { TopicsFtsEntity(
I think it makes the code cleaner to introduce an extension function to convert for fts entities?

Such as existing `fun Topic.asExternalModel()`

2023-04-21 08:58 UTC, closed without merging